Repository openyurtio/yurt-device-controller, pull requests merged in 2022-02, with the labels that each got.

#21 do not interrupt sync logic when non-fatal error occured
  controllers/device_syncer.go
  controllers/deviceprofile_syncer.go
  controllers/deviceservice_syncer.go
Labels: enhancement, lgtm, approved, size/S

#23 some enhancements when communication with edgex
  clients/edgex-foundry/device_client.go
  go.mod
Labels: size/M, lgtm, approved

#24 Feature: clean code for nodepoolindex
  controllers/device_syncer.go
  controllers/deviceprofile_syncer.go
  controllers/deviceservice_syncer.go
Labels: lgtm, approved, size/XS
