Repository openyurtio/yurt-device-controller, pull requests merged in 2022-08, with the labels that each got.

#43 refactor: upgrade kube-builder apiversion and project layout
  Makefile
  PROJECT
  README.md
  apis/device.openyurt.io/v1alpha1/device_types.go
  apis/device.openyurt.io/v1alpha1/deviceprofile_types.go
  apis/device.openyurt.io/v1alpha1/deviceservice_types.go
  apis/device.openyurt.io/v1alpha1/edgexobject.go
  apis/device.openyurt.io/v1alpha1/groupversion_info.go
  apis/device.openyurt.io/v1alpha1/zz_generated.deepcopy.go
  cmd/yurt-device-controller/app/core.go
  config/crd/bases/device.openyurt.io_deviceprofiles.yaml
  config/demo/manager.yaml
  config/rbac/valuedescriptor_editor_role.yaml
  config/rbac/valuedescriptor_viewer_role.yaml
  config/samples/colorchanger_demo/device.yaml
  config/samples/colorchanger_demo/deviceprofile.yaml
  config/samples/colorchanger_demo/deviceservice.yaml
  config/samples/colorchanger_demo/physicaldevice.yaml
  config/samples/colorchanger_demo/valuedescriptor.yaml
  config/samples/device_v1alpha1_device.yaml
  config/samples/device_v1alpha1_deviceprofile.yaml
  config/samples/device_v1alpha1_deviceservice.yaml
  config/samples/humidity_valuedescriptor.yaml
  config/samples/temperature_valuedescriptor.yaml
  config/samples/yurt-device-controller-beijing.yaml
  config/setup/crd.yaml
  go.mod
  go.sum
  pkg/clients/edgex-foundry/device_client.go
  pkg/clients/edgex-foundry/deviceprofile_client.go
  pkg/clients/edgex-foundry/deviceservice_client.go
  pkg/clients/edgex-foundry/util.go
  pkg/clients/errors.go
  pkg/clients/interface.go
  pkg/controllers/device_controller.go
  pkg/controllers/device_syncer.go
  pkg/controllers/deviceprofile_controller.go
  pkg/controllers/deviceprofile_syncer.go
  pkg/controllers/deviceservice_controller.go
  pkg/controllers/deviceservice_syncer.go
  pkg/controllers/predicate.go
  pkg/controllers/suite_test.go
  pkg/controllers/util/fieldindexer.go
  pkg/controllers/util/string.go
  pkg/controllers/util/tools.go
  pkg/controllers/well_known_labels.go
Labels: lgtm, approved

#51 fix golangci-lint warnings
  .github/workflows/ci.yaml
  cmd/yurt-device-controller/app/core.go
  go.mod
  go.sum
  pkg/clients/edgex-foundry/util.go
  pkg/controllers/device_controller.go
  pkg/controllers/device_controller_test.go
  pkg/controllers/device_syncer.go
  pkg/controllers/deviceprofile_controller.go
  pkg/controllers/deviceprofile_controller_test.go
  pkg/controllers/deviceprofile_syncer.go
  pkg/controllers/deviceservice_controller.go
  pkg/controllers/deviceservice_controller_test.go
  pkg/controllers/deviceservice_syncer.go
  pkg/controllers/predicate.go
Labels: size/L

#52 add approver and reviewer
  OWNERS
Labels: size/XS

#53 revise readme and update goreport badge
  README.md
Labels: lgtm, approved, size/XS

#55 use label to set edgex name (merge to branch main)
  pkg/clients/edgex-foundry/device_client.go
  pkg/clients/edgex-foundry/util.go
Labels: lgtm, approved, size/S

#56 add unit tests for edgex client
  .github/workflows/ci.yaml
  Makefile
  apis/device.openyurt.io/v1alpha1/groupversion_info.go
  go.mod
  go.sum
  pkg/clients/edgex-foundry/device_client.go
  pkg/clients/edgex-foundry/device_client_test.go
  pkg/clients/edgex-foundry/deviceprofile_client_test.go
  pkg/clients/edgex-foundry/deviceservice_client.go
  pkg/clients/edgex-foundry/deviceservice_client_test.go
  pkg/clients/edgex-foundry/util.go
Labels: lgtm, size/XL, approved
