Repository openyurtio/yurt-device-controller, pull requests merged in 2022-01, with the labels that each got.

#15 fix: deviceprofile_syncer should list deviceprofiles with fieldSelector spec.nodePool
  controllers/deviceprofile_controller.go
  controllers/deviceprofile_syncer.go
Labels: lgtm, approved, size/S

#17 Extract the configurable startup options and update the log tool
  clients/edgex-foundry/device_client.go
  clients/edgex-foundry/deviceprofile_client.go
  clients/edgex-foundry/deviceservice_client.go
  clients/edgex-foundry/util.go
  clients/edgex-foundry/valuedescriptor_client.go
  cmd/yurt-device-controller/app/core.go
  cmd/yurt-device-controller/options/options.go
  controllers/device_controller.go
  controllers/device_syncer.go
  controllers/deviceprofile_controller.go
  controllers/deviceprofile_syncer.go
  controllers/deviceservice_controller.go
  controllers/deviceservice_syncer.go
  controllers/predicate.go
  controllers/util/fieldindexer.go
  controllers/util/string.go
  controllers/util/tools.go
  controllers/valuedescriptor_controller.go
  go.mod
  go.sum
  main.go
Labels: enhancement, size/XXL, lgtm, approved

#19 Fix bug in deviceprofile synchronization process
  api/v1alpha1/deviceprofile_types.go
  controllers/device_syncer.go
  controllers/deviceprofile_controller.go
  controllers/deviceprofile_syncer.go
  controllers/deviceservice_syncer.go
Labels: bug, size/L, lgtm, approved

#20 fix issue 16:some items in deviceProperties do not have value
  clients/edgex-foundry/device_client.go
Labels: lgtm, approved, size/S
